### ISSUE TITLE
Text inside math constructs

### ISSUE THREAD

**Issue by imagingbook** [nlct/texparser#4]
Hello Nicola, I am still amazed about this massive piece of software -- thanks for sharing it!
In my target application it is essential to keep track of math/text mode all the time. One of my favorite tests (which all parsers sofar failed to pass) is a nested construct like this:
```
   some math $x = \text{some text} - \pi$ and so on ...
```
As I see, `texparser` properly finds the `\text` command inside the inline math group but does not switch to _text mode_ inside the following group. Is there any easy way to change this behaviour?

--Wilhelm

**Comment by nlct** [comment]
Thank you for your feedback. It's still very much experimental and a work in progress, but it's good to hear that it's useful :-)

`TeXParser` will identify `\text` as a control sequence but it currently isn't implemented so `TeXParser.getControlSequence("text")` will return `null` and `TeXParserListener.getControlSequence("text")` will return `TeXParserListener.createUndefinedCs("text")`. The argument will then simply be treated as a group (in math mode).

I've tried adding your inline example to the `test-article.tex` file. That won't interpret `\text` anyway as the test run in the Makefile sets it to use MathJax and the grouping from the argument is lost, which means it doesn't render correctly. (I'll have to make some adjustments to retain the grouping in math mode with the MathJax setting on.) Without MathJax, you'll get the error "Undefined command text".

I think this would need a new class in `latex/amsmath` (since it's an `amsmath` command) that creates a new group with the `TeXSetting` mode changed to `MODE_TEXT`. I'll look into it.

**Comment by imagingbook** [comment]
Thank you and YES, a good LaTeX parser in Java would indeed be very useful!

I had overlooked that `\text` was an AMS command, probably because I use it so much. And of course there are other commands like `\textrm`, `\mbox` etc. that should be considered in this context.

I admit that I had done these checks with an older version of your code and updated to the current status only a few days ago. However, to make it run in a standard IDE I had to restructure the project quite a bit. Also had to change a few package declarations to make it compile. If you are interested, the result can be found in this GitHub fork:

https://github.com/imagingbook/texparser-fork/tree/fixed-project-setup

If you think about changing your project setup I recommend to adopt the standard Maven layout (which I always use on my own projects) and Java 9 modules. I'd be glad to help if needed...

**Comment by imagingbook** [comment]
One other thing I wanted to mention: I was trying to build  my own `LaTeXParserListener` class (which is not supposed to output anything but build a syntax tree) modeled after class `LaTeX2LaTeX`. I noticed, however, that some of the classes in `texparserlib` (unnecessarily) depend on `LaTeX2LaTeX` itself! In some places this is easy to fix by declaring return values with a super-type, but a few problems remained. My quick fixes are in fork `develop` (https://github.com/imagingbook/texparser-fork/tree/develop), in this commit:

https://github.com/imagingbook/texparser-fork/commit/37960f305d3a5006ceafc4939a37e686e9627b4f

**Comment by nlct** [comment]
Thank you for your comments. I've had a look at Maven previously (the Island of TeX use it, so I ought to get a better understanding of it) but unfortunately I haven't had the time to look too deeply into it. My programming style was developed over 30 years ago with C, make, vi and bash ;-) and Maven is quite a structural shift from that (although I gather it can be used without an IDE). I tend to use Java 8 as a minimum version (rather than Java 9) as it's a Long-Term-Support (LTS) release. I'd prefer a higher LTS minimum (11 or 17) but in the past I had complaints when I moved up from 7 to 8 by users stuck with old systems that they couldn't update for some reason. (Mind you, that was a few years ago.)

Having said that, I'm not totally intransigent :-) and I appreciate your offer. One day I'll take you up on it if I can work out the best way of adjusting my workflow to it.

I do need to restructure the TeX Parser Library. It's evolved quite substantially from its original use. I think it could benefit from having the `texparserlib.jar` library split into, say `texparserlib.jar` (`lib/*`, `lib/primitives/*` and `lib/generic/*`), `texparserlatex.jar` (`lib/latex/*` and `lib/auxfile/*`), `texparserl2h.jar` (`lib/html`), `texparserbib.jar` (`lib/bib`) and `texparserl2l.jar` (`lib/latex2latex`). The other sub-directories aren't fully developed. This means I may have to move `CsvList` and `KeyValList` up a directory, as they're both used in `TeXParserUtils`. The LaTeX2LaTeX code isn't needed for most of my applications that use the TeX Parser Library (such as `bib2gls`) so it would be useful to split it. 

You original query has made me rethink the MathJax support. At the moment the html library is trying to interpret commands that should ideally be left to MathJax (which supports `\text` , `\mbox`, `\textrm` etc). I know this isn't actually what you were asking about, but it's prompted a line of thought ;-)

I've added support for `\text` (but haven't committed it yet). `\mbox` can be adjusted by adding a line to `FrameBox.applyToSettings` that sets the mode to text. For commands like `\textrm`, that would require changing the signature of `TextBlockCommand` to include a boolean that indicates the mode to switch to. (It can't always enforce a switch to text mode as, for example, `\textcolor` doesn't change out of math mode.)

At the moment I'm working on a new version of `datatool` so any changes in TeX Parser Lib for the next few months are likely to relate to `datatooltk` (as opposed to the updates last year that were for the benefit of `bib2gls`).

**Comment by nlct** [comment]
Implemented in commit bd83398b6727c5ea379eb71a083bde8cf5c2b6c2

I've now implemented `\text` (but it will only be available if `amsmath` is loaded) and also `TeXSetting.getCurrentMode()` should now return `TeXMode.TEXT` while inside the argument of text block commands such as `\textrm` and boxes such as `\mbox`.
